FROM node:18.16.0-alpine
WORKDIR /root/repo/
COPY . .
RUN apk upgrade \
    && apk add git \
    && apk add tzdata \
    && npm install -g @nestjs/cli \
    && apk add coreutils
ENTRYPOINT ["sleep", "infinity"]